### ISSUE TITLE
Add file headers and document the existing code base

### ISSUE THREAD

**Issue by akashkollipara** [VisorFolks/cyancore#9]
* Add File headers [[Use Doxygen syntax](https://www.doxygen.nl/manual/docblocks.html)]
>  
      /**
       * File Name: < 1 Tab > < name >
       * Description: < 1 Tab > < description >
       * < 2 Tab, align to start of description > < descrption-contd. >
       * Primary Author: < align >< name > [< email >]
       * Date: < use tab to align to start of largest subject >< Original Date of creation >
       */
      
       /**
        * < License > ...
        */

* Add Licenses to every file and framework.
* Document code and add function headers
>
       /**
        * <Function name> - 1 Liner description 
        * <Full Description >
        * <arg0>
        * <arg1>
        * ...
        * <return>
        */

**Comment by pranjalchanda08** [comment]
Hi @akashkollipara,

Try to used spaces instead of tabs, Generally multiple of 4 spaces are used instead of a tab.

Eg: 1 Tab = 4 space, 2 Tab = 8 Space and so on.

This will ensure that the user experience to read any portion of the code would be same irrespective of any platform.

To convert tabs to spaces you may use sublime text or any IDE that supports that change easily.

https://stackoverflow.com/a/56745999
